apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-kantin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-api
          # JANGAN LUPA: Ganti dengan username docker kamu!
          image: zahranz/kantin-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          # INJEKSI IDENTITAS (Tugas 2)
          env:
        - name: IDENTITAS
          value: "Zahran Zaidan Saputra - 2415429"
        - name: NAMA_KANTIN
          value: "Dota 2 Item Catalog"
        - name: MENU
          value: "Blink Dagger,Aghanim's Scepter,Monkey King Bar"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP # Ubah ke ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-kantin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-ui
          image: zahranz/kantin-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP # Ubah ke ClusterIP
